import pprint
from cookbook.recipes.schema import ObjectFilter

print("--- DIAGNOSTIC START ---")

# Check all filters generated by ObjectFilter
all_filters = ObjectFilter.get_filters()
keys = list(all_filters.keys())

print(f"Total Filters count: {len(keys)}")

# We expect factors like 'name', 'description', 'object_type', 'values'
# We do NOT expect 'object_type__name', 'values__value', etc. if they are part of a RelatedFilter

flat_related_filters = [k for k in keys if "__" in k]

if len(flat_related_filters) > 0:
    print("\n[FAILURE] Found flat snake_case filters for related fields:")
    for k in flat_related_filters:
        print(f"  - {k}")
else:
    print("\n[SUCCESS] No flat snake_case filters found for related fields.")

# Specifically check for the one the user mentioned (camelCased in their request but snake_case in Django)
# User mentioned objectType_Name_Contains. In Django this would be object_type__name__icontains or similar.
bad_key_example = "object_type__name__icontains"
if bad_key_example in all_filters:
    print(f"\n[FAILURE] Found {bad_key_example} in filters.")
else:
    print(f"\n[SUCCESS] {bad_key_example} is NOT in filters.")

print("--- DIAGNOSTIC END ---")
