import pprint
from cookbook.recipes.schema import ObjectFilter
from django_graphene_filters.filter_arguments_factory import FilterArgumentsFactory
from anytree import RenderTree

print("--- DIAGNOSTIC START ---")

# 1. Check if the RelatedFilter is detected
print(f"Related Filters detected: {list(ObjectFilter.related_filters.keys())}")

# 2. Check the expanded filters
all_filters = ObjectFilter.get_filters()
print(f"Total Filters count: {len(all_filters)}")

# 3. Check the trees generated by FilterArgumentsFactory
factory = FilterArgumentsFactory(ObjectFilter, "Object")
trees = factory.filterset_to_trees(ObjectFilter)

print("\nGenerated Trees:")
for tree in trees:
    for pre, fill, node in RenderTree(tree):
        print("%s%s" % (pre, node.name))

# 4. Check if a specific deep key is in the tree
found = False
for tree in trees:
    for node in tree.descendants:
        path = "__".join(n.name for n in node.path)
        if path == "object_type__description__icontains":
            found = True
            break
    if found: break

if found:
    print("\n[SUCCESS] Tree contains object_type__description__icontains")
else:
    print("\n[FAILURE] Tree is MISSING object_type__description__icontains")

print("--- DIAGNOSTIC END ---")
