# Generated by Django 6.0.1 on 2026-01-31 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="recipes.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects",
                to="recipes.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="recipes.attribute",
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="recipes.object",
            ),
        ),
    ]
