# Generated by Django 6.0.1 on 2026-01-31 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_alter_attribute_object_type_alter_object_object_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectss",
                to="recipes.objecttype",
            ),
        ),
    ]
