# Generated by Django 6.0.3 on 2026-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_object_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="object",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="value",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
